import type { NextApiRequest, NextApiResponse } from "next";
import { getServerSession } from "next-auth";
import { authOptions } from "@/lib/auth";
import { prisma } from "@/lib/prisma";

export default async function handler(req: NextApiRequest, res: NextApiResponse) {
  if (req.method !== "POST") return res.status(405).json({ error: "Method not allowed" });
  const session = await getServerSession(req, res, authOptions);
  if (!session?.user?.id) return res.status(401).json({ error: "Unauthorized" });

  const { token } = req.body;
  if (!token) return res.status(400).json({ error: "Please enter a token" });

  const t = token.toUpperCase().trim();

  if (!t.startsWith("GOGO-MONTHLY-") && !t.startsWith("GOGO-LIFETIME-")) {
    return res.status(400).json({ error: "Invalid token format. Please check and try again." });
  }

  const activationToken = await prisma.activationToken.findUnique({ where: { token: t } });
  if (!activationToken) {
    return res.status(400).json({ error: "Invalid token. This code was not generated by the system." });
  }
  if (activationToken.usedBy) {
    return res.status(400).json({ error: "This token has already been used." });
  }

  await prisma.activationToken.update({
    where: { id: activationToken.id },
    data: { usedBy: session.user.id, usedAt: new Date() },
  });

  const plan = "pro";
  const message = activationToken.type === "lifetime" ? "Lifetime Pro access unlocked!" : "Pro activated for 1 month!";

  await prisma.user.update({
    where: { id: session.user.id },
    data: { plan, subscriptionStatus: "active", subscriptionId: "token_" + t },
  });

  return res.json({ success: true, message });
}
